[package]
name = "legion_transform"
version = "0.3.0"
authors = ["Alec Thilenius <alec@thilenius.com>"]
edition = "2018"

license = "MIT"

[dependencies]
legion = { path = "../legion" }
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
rayon = "1.2.0"
serde = { version = "1", features = ["derive"] }
smallvec = "0.6"
log = "0.4"

[dev-dependencies]
env_logger = "0.7"
approx = "0.3"
ron = "0.5.1"
